export const PROPOSAL_WORKFLOW = {
    roles: [
        "planning_officer",
        "budget_officer",
        "chief_accountant",
        "agency_head",
        "dbm",
    ],
    transitions: {
        draft: {
            required_roles: [],
            on_submit: "pending_budget",
            on_approve: null,
            on_reject: null,
            allowed_access_levels: ["encode"],
            signatory_role: "",
        },
        pending_budget: {
            required_roles: ["budget_officer"],
            on_submit: null,
            on_approve: "pending_planning",
            on_reject: "draft",
            allowed_access_levels: ["encode"],
            signatory_role: "budget_officer",
        },
        pending_planning: {
            required_roles: ["planning_officer"],
            on_submit: null,
            on_approve: "pending_chief_accountant",
            on_reject: "draft",
            allowed_access_levels: ["encode"],
            signatory_role: "planning_officer",
        },
        pending_chief_accountant: {
            required_roles: ["chief_accountant"],
            on_submit: null,
            on_approve: "pending_agency_head",
            on_reject: "draft",
            allowed_access_levels: ["encode"],
            signatory_role: "chief_accountant",
        },
        pending_agency_head: {
            required_roles: ["agency_head"],
            on_submit: null,
            on_approve: "pending_dbm",
            on_reject: "draft",
            allowed_access_levels: ["approve"],
            signatory_role: "agency_head",
        },
        pending_dbm: {
            required_roles: ["dbm"],
            on_submit: null,
            on_approve: "approved",
            on_reject: "rejected",
            allowed_access_levels: ["review", "approve"],
            signatory_role: "dbm",
        },
        approved: {
            required_roles: [],
            on_submit: null,
            on_approve: null,
            on_reject: null,
            allowed_access_levels: [""],
            signatory_role: "",
        },
        rejected: {
            required_roles: [],
            on_submit: null,
            on_approve: null,
            on_reject: null,
            allowed_access_levels: [""],
            signatory_role: "",
        },
    },
};
